import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import CustomEmpty from '@/app/components/Empty';

import themeConfig from "./themeConfig";

import { inter } from "@/fe-global/assets/fonts";
import { ProviderRedux } from "@/app/reducers/providers";

export const metadata: Metadata = {
    title: "ALP Web Portal",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AntdRegistry>
                    <ConfigProvider theme={themeConfig} renderEmpty={CustomEmpty}>
                        <ProviderRedux>{children}</ProviderRedux>
                    </ConfigProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
